import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Autowired,
  ApiQueryParams,
  reply,
  type Ctx,
  Middleware,
} from '@forinda/kickjs'
import { ApiTags } from '@forinda/kickjs-swagger'
import { UsersService } from './users.service'
import { createUsersSchema } from './dtos/create-users.dto'
import { updateUsersSchema } from './dtos/update-users.dto'
import { USERS_QUERY_CONFIG } from './users.constants'
import { mdWare } from '@/middleware/md-ware.middleware'
import { myGuardGuard } from '@/guards/my-guard.guard'

// Each handler annotates its `ctx` with `Ctx<KickRoutes.UsersController['<method>']>`
// so `ctx.params`, `ctx.body`, and `ctx.query` are typed end-to-end.
// The `KickRoutes` namespace is generated by `kick typegen` (auto-run on
// `kick dev`) — see https://kickjs.app/guide/typegen.
//
// Handlers RETURN their payload rather than calling `ctx.json()`: the runtime
// auto-sends it, and `kick typegen` reads the return type to fill in
// `KickRoutes[...].response` — which is what makes the typed client know what
// each route gives back. A handler that writes via `ctx.json()` and returns
// nothing infers as `unknown`. Use `reply(status, body)` (or the
// `reply.created` / `reply.noContent` sugars) when the status isn't 200, and
// `ctx.problem.*` for error branches — those send immediately and return
// nothing, so they stay out of the success type.

@Controller()
export class UsersController {
  @Autowired() private readonly usersService!: UsersService

  @Get('/')
  @ApiTags('Users')
  @Middleware(myGuardGuard)
  @ApiQueryParams(USERS_QUERY_CONFIG)
  async list(ctx: Ctx<KickRoutes.UsersController['list']>) {
    return ctx.paginate(
      (parsed) => this.usersService.findPaginated(parsed),
      USERS_QUERY_CONFIG,
    )
  }

  @Get('/:id')
  @ApiTags('Users')
  async getById(ctx: Ctx<KickRoutes.UsersController['getById']>) {
    const result = await this.usersService.findById(ctx.params.id)
    if (!result) {
      // Sends RFC 9457 problem+json now; returning nothing keeps the 404 out
      // of this route's inferred response type.
      // ctx.problem.notFound({ detail: `Users ${ctx.params.id} not found` })
      return reply(404,'User not found')
      return
    }
    return result
  }

  @Post('/', { body: createUsersSchema, name: 'CreateUsers' })
  @ApiTags('Users')
  async create(ctx: Ctx) {
    return reply.created(await this.usersService.create(ctx.body))
  }

  @Put('/:id', { body: updateUsersSchema, name: 'UpdateUsers' })
  @ApiTags('Users')
  async update(ctx: Ctx<KickRoutes.UsersController['update']>) {
    return this.usersService.update(ctx.params.id, ctx.body)
  }

  @Delete('/:id')
  @ApiTags('Users')
  async remove(ctx: Ctx<KickRoutes.UsersController['remove']>) {
    await this.usersService.delete(ctx.params.id)
    return reply.noContent()
  }
}
